Issue #391: Add inclusive language check to PR's
architect/arc.codes pull request #393
Opened 2021-09-17 15:38 UTC by macdonst

Adds an inclusive language check to pull requests. 

See issue #391 for details.

2021-09-17 15:50 UTC, tbeseda commented
This LGTM. But I'm not well versed in Github Actions so I will defer :)

2021-09-17 16:28 UTC, filmaj approved these changes

2021-09-17 18:12 UTC, ryanbethel requested changes
Since we sometimes push code bypassing a PR I might change the trigger to:
```yaml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
```

2021-09-20 17:15 UTC, macdonst commented
@ryanbethel I updated the action with the change requested.

2021-09-21 17:41 UTC, merged